import {
  Customer,
  MenuItem,
  Order,
  RawIngredient,
  Recipe,
  Region,
  ItemModifier,
} from '../types';

export const INITIAL_REGIONS: Region[] = [
  { id: 'reg_yasmin', nameAr: 'حي الياسمين', nameEn: 'Al Yasmin', city: 'الرياض' },
  { id: 'reg_narjis', nameAr: 'حي النرجس', nameEn: 'Al Narjis', city: 'الرياض' },
  { id: 'reg_sahafa', nameAr: 'حي الصحافة', nameEn: 'Al Sahafa', city: 'الرياض' },
  { id: 'reg_malqa', nameAr: 'حي الملقا', nameEn: 'Al Malqa', city: 'الرياض' },
  { id: 'reg_hittin', nameAr: 'حي حطين', nameEn: 'Hittin', city: 'الرياض' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    name: 'خالد العتيبي',
    phone: '0501234567',
    region: 'حي الياسمين',
    creditLimit: 500,
    currentBalance: 120,
    notes: 'عميل دائم - يفضل حليب الشوفان',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-09-04T08:00:00Z',
  },
  {
    id: 'cust_2',
    name: 'محمد بن سالم',
    phone: '0559876543',
    region: 'حي النرجس',
    creditLimit: 600,
    currentBalance: 420,
    notes: 'طلبات سيارة منتظمة',
    createdAt: '2026-08-10T09:30:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
  },
  {
    id: 'cust_3',
    name: 'عبد الله القحطاني',
    phone: '0541122334',
    region: 'حي الصحافة',
    creditLimit: 1000,
    currentBalance: 0,
    notes: 'حساب شركة / سداد شهري',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-03T18:00:00Z',
  },
  {
    id: 'cust_4',
    name: 'فهد الدوسري',
    phone: '0565544332',
    region: 'حي الملقا',
    creditLimit: 400,
    currentBalance: 380,
    notes: 'قريب من بلوغ الحد الائتماني',
    createdAt: '2026-08-20T11:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'cust_5',
    name: 'سلطان الشمري',
    phone: '0533344556',
    region: 'حي حطين',
    creditLimit: 750,
    currentBalance: 215,
    notes: 'يسدد عبر مدى أسبوعياً',
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-09-04T13:30:00Z',
  },
];

export const INITIAL_INGREDIENTS: Record<string, RawIngredient> = {
  raw_coffee_beans: {
    id: 'raw_coffee_beans',
    nameAr: 'حبوب بن إسبريسو مختص',
    nameEn: 'Specialty Espresso Beans',
    sku: 'ING-ESP-01',
    unit: 'g',
    currentStock: 5000,
    minAlertThreshold: 1000,
    costPerUnit: 0.12,
  },
  raw_ethiopian_beans: {
    id: 'raw_ethiopian_beans',
    nameAr: 'حبوب بن إثيوبي مقطر V60',
    nameEn: 'Ethiopian V60 Beans',
    sku: 'ING-V60-01',
    unit: 'g',
    currentStock: 3000,
    minAlertThreshold: 500,
    costPerUnit: 0.16,
  },
  raw_fresh_milk: {
    id: 'raw_fresh_milk',
    nameAr: 'حليب طازج كامل الدسم',
    nameEn: 'Fresh Whole Milk',
    sku: 'ING-MLK-01',
    unit: 'ml',
    currentStock: 15000,
    minAlertThreshold: 3000,
    costPerUnit: 0.007,
  },
  raw_oat_milk: {
    id: 'raw_oat_milk',
    nameAr: 'حليب شوفان عضوي',
    nameEn: 'Organic Oat Milk',
    sku: 'ING-OAT-01',
    unit: 'ml',
    currentStock: 6000,
    minAlertThreshold: 1200,
    costPerUnit: 0.018,
  },
  raw_almond_milk: {
    id: 'raw_almond_milk',
    nameAr: 'حليب لوز غير محلى',
    nameEn: 'Almond Milk',
    sku: 'ING-ALM-01',
    unit: 'ml',
    currentStock: 4000,
    minAlertThreshold: 800,
    costPerUnit: 0.016,
  },
  raw_condensed_milk: {
    id: 'raw_condensed_milk',
    nameAr: 'حليب مكثف محلى',
    nameEn: 'Condensed Milk',
    sku: 'ING-CND-01',
    unit: 'ml',
    currentStock: 4000,
    minAlertThreshold: 800,
    costPerUnit: 0.02,
  },
  raw_pistachio_sauce: {
    id: 'raw_pistachio_sauce',
    nameAr: 'صوص بستاشيو إيطالي',
    nameEn: 'Pistachio Sauce',
    sku: 'ING-PIS-01',
    unit: 'ml',
    currentStock: 3000,
    minAlertThreshold: 600,
    costPerUnit: 0.04,
  },
  raw_caramel_drizzle: {
    id: 'raw_caramel_drizzle',
    nameAr: 'صوص الكراميل الذهبي',
    nameEn: 'Caramel Drizzle',
    sku: 'ING-CRM-01',
    unit: 'ml',
    currentStock: 2500,
    minAlertThreshold: 500,
    costPerUnit: 0.025,
  },
  raw_vanilla_syrup: {
    id: 'raw_vanilla_syrup',
    nameAr: 'سيروب فانيلا فرنسي',
    nameEn: 'French Vanilla Syrup',
    sku: 'ING-VAN-01',
    unit: 'ml',
    currentStock: 3000,
    minAlertThreshold: 500,
    costPerUnit: 0.02,
  },
  raw_cup_8oz: {
    id: 'raw_cup_8oz',
    nameAr: 'كوب ورقي 8 أونصة',
    nameEn: 'Paper Cup 8oz',
    sku: 'CUP-08',
    unit: 'piece',
    currentStock: 300,
    minAlertThreshold: 50,
    costPerUnit: 0.35,
  },
  raw_cup_12oz: {
    id: 'raw_cup_12oz',
    nameAr: 'كوب ورقي 12 أونصة',
    nameEn: 'Paper Cup 12oz',
    sku: 'CUP-12',
    unit: 'piece',
    currentStock: 400,
    minAlertThreshold: 60,
    costPerUnit: 0.4,
  },
  raw_cup_16oz_cold: {
    id: 'raw_cup_16oz_cold',
    nameAr: 'كوب شفاف بارد 16 أونصة',
    nameEn: 'Clear Cold Cup 16oz',
    sku: 'CUP-COLD-16',
    unit: 'piece',
    currentStock: 350,
    minAlertThreshold: 50,
    costPerUnit: 0.5,
  },
  raw_lid_hot: {
    id: 'raw_lid_hot',
    nameAr: 'غطاء أكواب ساخنة أسود',
    nameEn: 'Hot Cup Lid Black',
    sku: 'LID-HOT',
    unit: 'piece',
    currentStock: 800,
    minAlertThreshold: 100,
    costPerUnit: 0.15,
  },
  raw_lid_cold: {
    id: 'raw_lid_cold',
    nameAr: 'غطاء أكواب باردة مقبب',
    nameEn: 'Dome Cold Cup Lid',
    sku: 'LID-COLD',
    unit: 'piece',
    currentStock: 600,
    minAlertThreshold: 80,
    costPerUnit: 0.18,
  },
  raw_v60_filter: {
    id: 'raw_v60_filter',
    nameAr: 'فلتر ورقي V60 ياباني',
    nameEn: 'V60 Paper Filter',
    sku: 'FLT-V60',
    unit: 'piece',
    currentStock: 250,
    minAlertThreshold: 40,
    costPerUnit: 0.25,
  },
  raw_croissant_butter: {
    id: 'raw_croissant_butter',
    nameAr: 'كرواسون زبدة فرنسي مسبق الخبز',
    nameEn: 'Butter Croissant Unit',
    sku: 'BAK-CR-01',
    unit: 'piece',
    currentStock: 35,
    minAlertThreshold: 8,
    costPerUnit: 4.5,
  },
  raw_cookie_chocolate: {
    id: 'raw_cookie_chocolate',
    nameAr: 'كوكيز شوكولاتة بلجيكية',
    nameEn: 'Belgian Chocolate Cookie',
    sku: 'BAK-CK-01',
    unit: 'piece',
    currentStock: 45,
    minAlertThreshold: 10,
    costPerUnit: 4.0,
  },
};

export const COMMON_MODIFIERS: ItemModifier[] = [
  // Milk Choices
  { id: 'mod_whole_milk', category: 'MILK', nameAr: 'حليب عادي', nameEn: 'Whole Milk', priceDelta: 0 },
  { id: 'mod_oat_milk', category: 'MILK', nameAr: 'حليب شوفان', nameEn: 'Oat Milk', priceDelta: 4 },
  { id: 'mod_almond_milk', category: 'MILK', nameAr: 'حليب لوز', nameEn: 'Almond Milk', priceDelta: 4 },

  // Sweetness
  { id: 'mod_sweet_0', category: 'SWEETNESS', nameAr: 'بدون سكر (0%)', nameEn: 'No Sugar (0%)', priceDelta: 0 },
  { id: 'mod_sweet_50', category: 'SWEETNESS', nameAr: 'سُكّر خفيف (50%)', nameEn: 'Half Sweet (50%)', priceDelta: 0 },
  { id: 'mod_sweet_100', category: 'SWEETNESS', nameAr: 'سُكّر قياسي (100%)', nameEn: 'Standard Sweet (100%)', priceDelta: 0 },
  { id: 'mod_sweet_150', category: 'SWEETNESS', nameAr: 'سُكّر زيادة (150%)', nameEn: 'Extra Sweet (150%)', priceDelta: 0 },

  // Temperature
  { id: 'mod_temp_hot', category: 'TEMPERATURE', nameAr: 'ساخن 🔥', nameEn: 'Hot', priceDelta: 0 },
  { id: 'mod_temp_iced', category: 'TEMPERATURE', nameAr: 'مثلج ❄️', nameEn: 'Iced', priceDelta: 0 },

  // Extra Shots & Syrups
  { id: 'mod_extra_shot', category: 'EXTRA_SHOT', nameAr: 'شوت إسبريسو إضافي', nameEn: 'Extra Espresso Shot', priceDelta: 4 },
  { id: 'mod_syrup_vanilla', category: 'SYRUP', nameAr: 'سيروب فانيلا', nameEn: 'Vanilla Syrup', priceDelta: 3 },
  { id: 'mod_syrup_caramel', category: 'SYRUP', nameAr: 'كراميل إضافي', nameEn: 'Extra Caramel', priceDelta: 3 },
];

export const INITIAL_RECIPES: Record<string, Recipe> = {
  rec_spanish_latte: {
    id: 'rec_spanish_latte',
    menuItemId: 'item_spanish_latte',
    nameAr: 'وصفة سبانش لاتيه',
    nameEn: 'Spanish Latte Recipe',
    baseIngredients: [
      { ingredientId: 'raw_coffee_beans', quantityRequired: 18 },
      { ingredientId: 'raw_fresh_milk', quantityRequired: 150 },
      { ingredientId: 'raw_condensed_milk', quantityRequired: 30 },
      { ingredientId: 'raw_cup_12oz', quantityRequired: 1 },
      { ingredientId: 'raw_lid_hot', quantityRequired: 1 },
    ],
    modifierAdjustments: {
      mod_oat_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -150 },
        { ingredientId: 'raw_oat_milk', quantityRequired: 150 },
      ],
      mod_almond_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -150 },
        { ingredientId: 'raw_almond_milk', quantityRequired: 150 },
      ],
      mod_extra_shot: [
        { ingredientId: 'raw_coffee_beans', quantityRequired: 9 },
      ],
      mod_temp_iced: [
        { ingredientId: 'raw_cup_12oz', quantityRequired: -1 },
        { ingredientId: 'raw_lid_hot', quantityRequired: -1 },
        { ingredientId: 'raw_cup_16oz_cold', quantityRequired: 1 },
        { ingredientId: 'raw_lid_cold', quantityRequired: 1 },
      ],
    },
  },
  rec_flat_white: {
    id: 'rec_flat_white',
    menuItemId: 'item_flat_white',
    nameAr: 'وصفة فلات وايت',
    nameEn: 'Flat White Recipe',
    baseIngredients: [
      { ingredientId: 'raw_coffee_beans', quantityRequired: 18 },
      { ingredientId: 'raw_fresh_milk', quantityRequired: 130 },
      { ingredientId: 'raw_cup_8oz', quantityRequired: 1 },
      { ingredientId: 'raw_lid_hot', quantityRequired: 1 },
    ],
    modifierAdjustments: {
      mod_oat_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -130 },
        { ingredientId: 'raw_oat_milk', quantityRequired: 130 },
      ],
      mod_almond_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -130 },
        { ingredientId: 'raw_almond_milk', quantityRequired: 130 },
      ],
      mod_extra_shot: [
        { ingredientId: 'raw_coffee_beans', quantityRequired: 9 },
      ],
    },
  },
  rec_v60_ethiopian: {
    id: 'rec_v60_ethiopian',
    menuItemId: 'item_v60_ethiopian',
    nameAr: 'وصفة قهوة مقطرة V60',
    nameEn: 'V60 Drip Recipe',
    baseIngredients: [
      { ingredientId: 'raw_ethiopian_beans', quantityRequired: 20 },
      { ingredientId: 'raw_v60_filter', quantityRequired: 1 },
      { ingredientId: 'raw_cup_12oz', quantityRequired: 1 },
      { ingredientId: 'raw_lid_hot', quantityRequired: 1 },
    ],
    modifierAdjustments: {
      mod_temp_iced: [
        { ingredientId: 'raw_cup_12oz', quantityRequired: -1 },
        { ingredientId: 'raw_lid_hot', quantityRequired: -1 },
        { ingredientId: 'raw_cup_16oz_cold', quantityRequired: 1 },
        { ingredientId: 'raw_lid_cold', quantityRequired: 1 },
      ],
    },
  },
  rec_caramel_macchiato: {
    id: 'rec_caramel_macchiato',
    menuItemId: 'item_caramel_macchiato',
    nameAr: 'وصفة كاراميل ماكياتو',
    nameEn: 'Caramel Macchiato Recipe',
    baseIngredients: [
      { ingredientId: 'raw_coffee_beans', quantityRequired: 18 },
      { ingredientId: 'raw_fresh_milk', quantityRequired: 160 },
      { ingredientId: 'raw_vanilla_syrup', quantityRequired: 25 },
      { ingredientId: 'raw_caramel_drizzle', quantityRequired: 15 },
      { ingredientId: 'raw_cup_16oz_cold', quantityRequired: 1 },
      { ingredientId: 'raw_lid_cold', quantityRequired: 1 },
    ],
    modifierAdjustments: {
      mod_oat_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -160 },
        { ingredientId: 'raw_oat_milk', quantityRequired: 160 },
      ],
      mod_extra_shot: [
        { ingredientId: 'raw_coffee_beans', quantityRequired: 9 },
      ],
    },
  },
  rec_pistachio_latte: {
    id: 'rec_pistachio_latte',
    menuItemId: 'item_pistachio_latte',
    nameAr: 'وصفة بستاشيو لاتيه',
    nameEn: 'Pistachio Latte Recipe',
    baseIngredients: [
      { ingredientId: 'raw_coffee_beans', quantityRequired: 18 },
      { ingredientId: 'raw_fresh_milk', quantityRequired: 150 },
      { ingredientId: 'raw_pistachio_sauce', quantityRequired: 30 },
      { ingredientId: 'raw_cup_12oz', quantityRequired: 1 },
      { ingredientId: 'raw_lid_hot', quantityRequired: 1 },
    ],
    modifierAdjustments: {
      mod_oat_milk: [
        { ingredientId: 'raw_fresh_milk', quantityRequired: -150 },
        { ingredientId: 'raw_oat_milk', quantityRequired: 150 },
      ],
      mod_extra_shot: [
        { ingredientId: 'raw_coffee_beans', quantityRequired: 9 },
      ],
      mod_temp_iced: [
        { ingredientId: 'raw_cup_12oz', quantityRequired: -1 },
        { ingredientId: 'raw_lid_hot', quantityRequired: -1 },
        { ingredientId: 'raw_cup_16oz_cold', quantityRequired: 1 },
        { ingredientId: 'raw_lid_cold', quantityRequired: 1 },
      ],
    },
  },
  rec_croissant: {
    id: 'rec_croissant',
    menuItemId: 'item_croissant',
    nameAr: 'كرواسون زبدة',
    nameEn: 'Butter Croissant',
    baseIngredients: [
      { ingredientId: 'raw_croissant_butter', quantityRequired: 1 },
    ],
  },
  rec_cookie: {
    id: 'rec_cookie',
    menuItemId: 'item_cookie',
    nameAr: 'كوكيز شوكولاتة',
    nameEn: 'Chocolate Cookie',
    baseIngredients: [
      { ingredientId: 'raw_cookie_chocolate', quantityRequired: 1 },
    ],
  },
};

export const INITIAL_MENU: MenuItem[] = [
  {
    id: 'item_spanish_latte',
    category: 'HOT',
    nameAr: 'سبانش لاتيه',
    nameEn: 'Spanish Latte',
    descriptionAr: 'إسبريسو غني مع حليب مبخر وحليب مكثف محلى',
    descriptionEn: 'Rich espresso with steamed milk and sweetened condensed milk',
    basePrice: 20,
    sizes: { S: 18, M: 20, L: 23 },
    recipeId: 'rec_spanish_latte',
    isAvailable: true,
  },
  {
    id: 'item_flat_white',
    category: 'HOT',
    nameAr: 'فلات وايت',
    nameEn: 'Flat White',
    descriptionAr: 'دبل ريستريتو مع حليب مخملي سلس بنسبة متوازنة',
    descriptionEn: 'Double ristretto with micro-foamed silky milk',
    basePrice: 17,
    sizes: { S: 17, M: 19, L: 21 },
    recipeId: 'rec_flat_white',
    isAvailable: true,
  },
  {
    id: 'item_v60_ethiopian',
    category: 'DRIP',
    nameAr: 'قهوة مقطرة V60 إثيوبية',
    nameEn: 'V60 Ethiopian Drip',
    descriptionAr: 'محصول يرقاتشيفي بقوام ناعم وإيحاءات الفواكه المجففة',
    descriptionEn: 'Yirgacheffe origin with fruity notes and floral finish',
    basePrice: 22,
    sizes: { S: 22, M: 25, L: 28 },
    recipeId: 'rec_v60_ethiopian',
    isAvailable: true,
  },
  {
    id: 'item_caramel_macchiato',
    category: 'COLD',
    nameAr: 'كاراميل ماكياتو مثلج',
    nameEn: 'Iced Caramel Macchiato',
    descriptionAr: 'طبقات من الفانيلا والحليب البارد مع شوت إسبريسو وكراميل',
    descriptionEn: 'Layered vanilla, chilled milk, fresh espresso and caramel drizzle',
    basePrice: 24,
    sizes: { S: 22, M: 24, L: 27 },
    recipeId: 'rec_caramel_macchiato',
    isAvailable: true,
  },
  {
    id: 'item_pistachio_latte',
    category: 'HOT',
    nameAr: 'بستاشيو لاتيه',
    nameEn: 'Pistachio Latte',
    descriptionAr: 'إسبريسو مختص مع صوص الفستق الإيطالي وحليب كريمي',
    descriptionEn: 'Specialty espresso with authentic pistachio sauce and cream milk',
    basePrice: 25,
    sizes: { S: 23, M: 25, L: 28 },
    recipeId: 'rec_pistachio_latte',
    isAvailable: true,
  },
  {
    id: 'item_croissant',
    category: 'PASTRY',
    nameAr: 'كرواسون زبدة فرنسي',
    nameEn: 'French Butter Croissant',
    descriptionAr: 'مقرمش وهش ومخبوز طازجاً بزبدة بريتاني الفاخرة',
    descriptionEn: 'Crispy, flaky and freshly baked with French Brittany butter',
    basePrice: 14,
    sizes: { S: 14, M: 14, L: 14 },
    recipeId: 'rec_croissant',
    isAvailable: true,
  },
  {
    id: 'item_cookie',
    category: 'PASTRY',
    nameAr: 'كوكيز شوكولاتة بلجيكية',
    nameEn: 'Belgian Chocolate Cookie',
    descriptionAr: 'كوكيز طري ومحشو بقطع الشوكولاتة البلجيكية الداكنة',
    descriptionEn: 'Soft-baked cookie loaded with rich Belgian dark chocolate',
    basePrice: 12,
    sizes: { S: 12, M: 12, L: 12 },
    recipeId: 'rec_cookie',
    isAvailable: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    orderNumber: 101,
    formattedOrderNumber: '#101',
    status: 'IN_PREPARATION',
    createdAt: new Date(Date.now() - 120 * 1000).toISOString(), // 2 minutes ago
    updatedAt: new Date(Date.now() - 120 * 1000).toISOString(),
    preparationStartedAt: new Date(Date.now() - 120 * 1000).toISOString(),
    stationId: 'DRIVE_THRU_1',
    attendantName: 'أحمد',
    tagType: 'VEHICLE',
    tagValue: 'أ ب ج 1234',
    vehicleModel: 'تويوتا كامري بيضاء',
    items: [
      {
        id: 'ord_item_1',
        menuItemId: 'item_spanish_latte',
        nameAr: 'سبانش لاتيه',
        nameEn: 'Spanish Latte',
        unitPrice: 20,
        quantity: 1,
        size: 'M',
        modifiers: [
          { id: 'mod_oat_milk', category: 'MILK', nameAr: 'حليب شوفان', nameEn: 'Oat Milk', priceDelta: 4 },
          { id: 'mod_temp_hot', category: 'TEMPERATURE', nameAr: 'ساخن 🔥', nameEn: 'Hot', priceDelta: 0 },
        ],
        specialInstructions: 'حار جداً',
        totalPrice: 24,
      },
    ],
    subtotal: 20.87,
    tax: 3.13,
    total: 24.0,
    paymentStatus: 'UNPAID',
    notes: 'طلب سيارة مسار 1',
  },
  {
    id: 'ord_102',
    orderNumber: 102,
    formattedOrderNumber: '#102',
    status: 'READY_FOR_PICKUP',
    createdAt: new Date(Date.now() - 320 * 1000).toISOString(), // ~5.3 minutes ago
    updatedAt: new Date(Date.now() - 60 * 1000).toISOString(),
    preparationStartedAt: new Date(Date.now() - 320 * 1000).toISOString(),
    readyAt: new Date(Date.now() - 60 * 1000).toISOString(),
    prepDurationSeconds: 260,
    stationId: 'DRIVE_THRU_1',
    attendantName: 'سارة',
    tagType: 'VEHICLE',
    tagValue: 'س ص ع 5566',
    vehicleModel: 'لكزس سوداء',
    items: [
      {
        id: 'ord_item_2',
        menuItemId: 'item_caramel_macchiato',
        nameAr: 'كاراميل ماكياتو مثلج',
        nameEn: 'Iced Caramel Macchiato',
        unitPrice: 24,
        quantity: 1,
        size: 'M',
        modifiers: [
          { id: 'mod_temp_iced', category: 'TEMPERATURE', nameAr: 'مثلج ❄️', nameEn: 'Iced', priceDelta: 0 },
          { id: 'mod_extra_shot', category: 'EXTRA_SHOT', nameAr: 'شوت إضافي', nameEn: 'Extra Shot', priceDelta: 4 },
        ],
        totalPrice: 28,
      },
      {
        id: 'ord_item_3',
        menuItemId: 'item_cookie',
        nameAr: 'كوكيز شوكولاتة بلجيكية',
        nameEn: 'Belgian Chocolate Cookie',
        unitPrice: 12,
        quantity: 1,
        size: 'M',
        modifiers: [],
        totalPrice: 12,
      },
    ],
    subtotal: 34.78,
    tax: 5.22,
    total: 40.0,
    paymentStatus: 'UNPAID',
    notes: 'نافذة الاستلام جاهز',
  },
];
